---
- name: Add certbot repository
  apt_repository:
    repo: 'ppa:certbot/certbot'
    state: present

- name: Install certbot
  package:
    name: "certbot=0.28.0-1+ubuntu{{ ansible_distribution_version }}.1+certbot+4"
    state: present

- name: Install certbot-nginx plugin
  package:
    name: "python-certbot-nginx=0.28.0-1+ubuntu{{ ansible_distribution_version }}.1+certbot+3"
    state: present

- import_tasks: certificate.yml
  when: domain_name is defined
