---
- name: Add certbot repository
  apt_repository:
    repo: 'ppa:certbot/certbot'
    state: present

- name: Install certbot
  package:
    name: certbot=0.26.1-1+ubuntu16.04.1+certbot+2
    state: present

- name: Install certbot-nginx plugin
  package:
    name: python-certbot-nginx=0.25.0-2+ubuntu16.04.1+certbot+1
    state: present

- name: Check if certificate already exists
  stat:
    path: "/etc/letsencrypt/live/{{ certbot_nginx_cert_name | default(domain_name) }}/cert.pem"
  register: letsencrypt_cert

- name: Generate new certificate if one doesn't exist
  shell: "certbot certonly --nginx --email '{{ letsencrypt_email }}' --agree-tos -d '{{ domain_name }}' {% if certbot_nginx_cert_name %} --cert-name '{{ certbot_nginx_cert_name }}' {% endif %} {% if letsencrypt_staging %} --staging {% endif %}"
  when: not letsencrypt_cert.stat.exists
