---
- name: Add certbot repository
  apt_repository:
    repo: 'ppa:certbot/certbot'
    state: present

- name: Install certbot
  package:
    name: "certbot={{ certbot_version }}"
    state: present

- name: Install certbot-nginx plugin
  package:
    name: "python-certbot-nginx={{ certbot_nginx_version }}"
    state: present

- import_tasks: certificate.yml
  when: domain_name is defined
