---
- name: Add certbot repository
  apt_repository:
    repo: 'ppa:certbot/certbot'
    state: present

- name: Install certbot
  package:
    name: letsencrypt
    state: present

- name: Install certbot-nginx plugin
  package:
    name: python-certbot-nginx
    state: present

- name: Check if certificate already exists
  stat:
    path: "/etc/letsencrypt/live/{{ domain_name }}/cert.pem"
  register: letsencrypt_cert

- name: Generate new certificate if one doesn't exist
  shell: "certbot certonly --nginx --cert-name {{ cert_name }} --email {{ letsencrypt_email }} --agree-tos -d {{ domain_name }} {% if letsencrypt_staging %} --staging {% endif %}"
  when: not letsencrypt_cert.stat.exists
